name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Dhaka
    permissions:
      contents: read
    steps:
      - name: Checkout private stats updater
        uses: actions/checkout@v7
        with:
          repository: circle-earth/waka-readme-stats
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: waka-readme-stats
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: waka-readme-stats/requirements.txt

      - name: Install dependencies
        run: python -m pip install -r waka-readme-stats/requirements.txt

      - name: Update README with dev metrics
        run: python waka-readme-stats/sources/main.py
        env:
          INPUT_WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          INPUT_GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INPUT_LOCALE: "en"
